name: Deploy to GoDaddy FTP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: front
        run: npm install --legacy-peer-deps

      - name: Build React app
        working-directory: front
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      - name: Upload to GoDaddy FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          local-dir: front/build
